### ISSUE TITLE
missing image on docker hub

### ISSUE THREAD

**Issue by ReSearchITEng** [thumbsup/docker#1]
I've created one using your Dockerfile with version 1.x.x which, as of 1st of April 2017, translated to 1.1.2 .

docker pull researchiteng/thumbsup:1.1.2 #(same with :latest right now, as 2.0.0 has issues and I did not upload it - see issue opened for 2.0.0)

**Comment by rprieto** [comment]
Thanks for raising the issue. Sorry I only noticed it now. I think it should be OK now, the image is published as https://hub.docker.com/r/thumbsupgallery/thumbsup/ .
